# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - main
      - 'release/*' # Automatically deploy for branches starting with "release/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: yarn install
      - run: git config --global user.name "darkmortal"
      - run: git config --global user.email "dragonbeast.saiyan@gmail.com"
      - run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
